apiVersion: apps/v1
kind: Deployment
metadata:
   name: mongodb
spec: 
  selector:
    matchLabels:
     app: mongodb
  replicas: 1
  template: 
     metadata:
        labels:
          app: mongodb
     spec: 
       containers:
       - name: mongodb
         image: mongo:latest 
         volumeMounts:  
          - name:  mongo-persistent-storage
            mountPath: /data/db  
       volumes:
        - name: mongo-persistent-storage
          persistentVolumeClaim:
             claimName: mongo-pvc

---
kind: Service
apiVersion: v1
metadata:
  name: fleetman-mongodb
spec: 
  selector:
    app: mongodb
  ports:
   - name: mongoport  
     port: 27017
  type: ClusterIP     


